### ISSUE TITLE
Add missing methods?

### ISSUE THREAD

**Issue by fidian** [heycalmdown/node-confluence#15]
My problem is that I need to convert a large site into Confluence markup and I will be doing this repeatedly to make sure the content stays updated. Confluence is not the authoritative source, which is why I need to reimport this data over and over. Your library looks like it provides about half of what I need, especially around getting children of pages and getting all pages in a space.

I was looking at [confluence-api](https://github.com/johnpduane/confluence-api) and they have useful functions that I will need for my project. Specifically, the ability to update a page and dealing with attachments. Do you think you could add that functionality to your library instead of me using both? Right now it appears that I will be using two Confluence libraries in order to scan for all pages (confluency), upload new pages by title (confluence-api), change page parents (both) and delete pages (both).

**Comment by heycalmdown** [comment]
Thanks for having interest. I'll look into it as soon as possible, but it seems easy.

**Comment by fidian** [comment]
I am unsure if there are more functions that are needed by others. My needs have been met. Closing issue.
